<?php

return array(
	'version' => '0.9.4.1',
	'plugin.type' => '',
	'pgcache.enabled' => true,
	'pgcache.engine' => 'file_generic',
	'minify.enabled' => true,
	'minify.auto' => true,
	'minify.engine' => 'file',
	'minify.html.engine' => 'html',
	'minify.js.engine' => 'js',
	'minify.css.engine' => 'css',
	'dbcache.enabled' => false,
	'dbcache.engine' => 'file',
	'objectcache.enabled' => true,
	'objectcache.engine' => 'file',
	'browsercache.enabled' => true,
	'cdn.enabled' => false,
	'cdn.engine' => 'maxcdn',
	'varnish.enabled' => false,
	'varnish.servers' => array(
		0 => '',
	),
	'newrelic.enabled' => false,
	'newrelic.api_key' => '',
	'newrelic.account_id' => '',
	'newrelic.appname' => '',
	'newrelic.application_id' => 0,
	'plugin.license_key' => '',
	'widget.pagespeed.enabled' => true,
	'widget.pagespeed.key' => '',
	'config.check' => true,
	'pgcache.file.nfs' => false,
	'minify.file.nfs' => false,
	'dbcache.file.locking' => false,
	'objectcache.file.locking' => false,
	'pgcache.file.locking' => false,
	'minify.file.locking' => false,
	'common.instance_id' => 1313124757,
	'notes.need_empty_pgcache' => false,
	'notes.support_us' => false,
	'notes.plugins_updated' => false,
);