<?php

// Require WP Load First
$current_url = dirname( __FILE__ );
$wp_content_pos = strpos( $current_url, 'wp-content' );
$wp_content = substr( $current_url, 0, $wp_content_pos );
require_once( $wp_content . 'wp-load.php' );

// Revert Back to Stylesheet
ob_start ( "ob_gzhandler" );
header( "Content-type: text/css; charset: UTF-8" );

// Grab the HEX color value from theme options
$accent = of_get_option( 'accent-color' );

?>


/*-----------------------------------------------------------------
 These are dynamic accent color values generated by theme options
-----------------------------------------------------------------*/

a {
	color: <?php echo $accent; ?>;
	}

::selection { 
	background: <?php echo $accent; ?>;
	}

a.btn,
input[type="submit"],
button.btn,
.more-link {
	background-color: <?php echo $accent; ?>;
	}

#header .logo a {
	border-bottom-color: <?php echo $accent; ?>;
	}

#header #nav li a:hover {
	color: <?php echo $accent; ?>;
	}

#header #nav li.current_page_item a,
#header #nav li.current-menu-parent a,
#header #nav li.current_page_parent a {
	color: <?php echo $accent; ?>;
	}

#header #nav ul li.current-menu-item a {
	color: <?php echo $accent; ?> !important !important;
	}

body.home #hero .flexslider .slide a .overlay {
	background: <?php echo $accent; ?>;
	}

body.home #blog .entry-title a:hover {
	color: <?php echo $accent; ?>;
	}

#content article h2.entry-title a:hover {
	color: <?php echo $accent; ?>;
	}

#content article .entry-content blockquote {
	border-left-color: <?php echo $accent; ?>;
	}

#content article.format-quote .entry-title a:hover blockquote p {
	color: <?php echo $accent; ?>;
	}

#content article.format-link .entry-image p a {
	background: <?php echo $accent; ?>;
	}

.mejs-time-current {
	background: <?php echo $accent; ?> !important;
	}

.mejs-controls .mejs-horizontal-volume-slider .mejs-horizontal-volume-current {
	background: <?php echo $accent; ?> !important;
	}

.flex-direction-nav a:hover {
	background-color: <?php echo $accent; ?>;
	}

.mighty_project_widget .post a .overlay {
	background: <?php echo $accent; ?>;
	}

.mighty_project_widget .post a:hover .overlay {
	background: <?php echo $accent; ?>;
	}

.mighty_social_widget a:hover {
	background: <?php echo $accent; ?>;
	}

body.page-template-template-portfolio-sortable-php .portfolio-filter li a.active,
body.page-template-template-portfolio-sortable-php .portfolio-filter li a:hover {
	color: <?php echo $accent; ?>;
	}

body.page-template-template-portfolio-php .item a .overlay,
body.single-portfolio .item a .overlay {
	background: <?php echo $accent; ?>;
	}

body.page-template-template-portfolio-php .item a:hover .overlay,
body.single-portfolio .item a:hover .overlay {
	background: <?php echo $accent; ?>;
	}

#footer nav li a:hover,
#footer nav li.current-menu-item a {
	color: <?php echo $accent; ?>;
	}


/* Responsive */

@media only screen and (max-width: 999px) {

	a.slicknav_btn:hover .slicknav_icon-bar {
		background: <?php echo $accent; ?>;
	}

	.slicknav_nav .slicknav_arrow {
		color: <?php echo $accent; ?>;
	}

}
